### ISSUE TITLE
Bug: Breaks with Axios 0.22.2

### ISSUE THREAD

**Issue by bmpieretti** [D-Pow/MockRequests#16]
In axios 0.22.2, an update was made that stops mocked requests from being resolved correctly. In [this pr that was released with 0.22.2](https://github.com/axios/axios/commit/5ad6994da3e97b8ed857faed90955a65a891f459#diff-2175f7ecc915e8b17c9831b9bbcd0a681759f7227a424964b04ab68e8166dd77R37), you will notice that axios now relies on the xhr requests [onloadend event](https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L62) over the `onreadystatechange` event, which causes this.

In mock-requests, you rely on the `onreadystatechange` [here](https://github.com/D-Pow/MockRequests/blob/master/src/MockRequests.js#L428) to resolve the subbed requests. I can fix this by pulling this lib into my project and updating that line to resolve via the `onloadend` callback, but I don't currently have bandwidth or great understanding of when to use one vs the other in this context, and would be awesome if you could take a look at supporting both.

Let me know if I can assist in any way!

**Comment by D-Pow** [comment]
Thanks for letting me know, @bmpieretti! It seems like an easy enough fix to do fairly quickly, investigating this now.

**Comment by D-Pow** [comment]
This should be fixed in [PR #17](https://github.com/D-Pow/MockRequests/pull/17). Please let me know if you still encounter any issues!
